package student_anvars_intezars.home_tasks.lesson_12.task_20;

public class MultiCatchExample {

    /*try {

    } catch (Exception e) {

    } catch (ArithmeticException a) {

    }
    Данный код, который указан выше не откомпилируется, так как первый кетчер словит любое исключение
    типо Exception даже ArithmeticException.
    Второй кетчер никогда не будет осуществлен. Код не будет компилироваться
    */
}
